export const config = {
  ALCHEMY_API_KEY: process.env.REACT_APP_ALCHEMY_API_KEY ?? "",
  INFURA_LINK: process.env.REACT_APP_INFURA_LINK ?? "",
  CUSTONOMY_PROJECT_ID: process.env.REACT_APP_CUSTONOMY_PROJECT_ID ?? "",
  CUSTONOMY_API_KEY: process.env.REACT_APP_CUSTONOMY_API_KEY ?? "",
  CUSTONOMY_END_POINT: process.env.REACT_APP_CUSTONOMY_END_POINT ?? "",
  CUSTONOMY_WIDGET_URL: process.env.REACT_APP_CUSTONOMY_WIDGET_URL ?? "",
  API_BASE_URL: process.env.REACT_APP_API_BASE_URL ?? "",
  CHAIN_ID: process.env.REACT_APP_CHAIN_ID ?? '0x13881',
  CONTRACT: {
    LUCKY_CAT: process.env.REACT_APP_CONTRACT_LUCKY_CAT ?? "0x5846Ad84c95f1886C08407a32e7B4864243264df",
    LUCKY_CHIPMUNK: process.env.REACT_APP_CONTRACT_LUCKY_CHIPMUNK ?? "0xA17CDB459baf43f1ed573594f1d4532cB1f5291f",
    LUCKY_CRAB: process.env.REACT_APP_CONTRACT_LUCKY_CRAB ?? "0xcb39c9013eEf12743fE87eD4468D3e4Cea58cBAd",
  },
};
